env:
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:  
  import/extensions: 0
  no-console: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
